### ISSUE TITLE
Extending Syntax to define actions to execute

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#366]
**Is your feature request related to a problem? Please describe.**
--feed-sel commandline parameter currently allows to select actions to execute based on metadata.feed configurations. SDL should allow advanced syntax to select actions.

**Describe the solution you'd like**
Implement selecting actions based on id, metadata.name, outputs.metadata.layer, start from a certain action, end with a certain action, start from a certain dataobject...

**Comment by zzeekk** [comment]
Suggested command line is
```
  -f, --feed-sel <value>   Select actions to execute by one or multiple expressions separated by semicolon (;). Results from multiple expressions are combined from left to right.
                           Expression syntax: \"<operation?><prefix:?><regex>\"
                           Operations:
                           - pipe symbol (|): the two sets are combined by union operation (default)
                           - ampersand symbol (&): the tow sets are combined by intersection operation
                           - minus symbol (-): the second set is subtracted from the first set
                           Prefixes:
                           - 'feeds': select actions where metadata.feed is matched by regex pattern (default)
                           - 'names': select actions where metadata.name is matched by regex pattern
                           - 'ids': select actions where id is matched by regex pattern
                           - 'layers': select actions where metadata.layer of all output DataObjects is matched by regex pattern
                           - 'startFromActionIds': select actions which with id is matched by regex pattern and any dependent action (=successors)
                           - 'endWithActionIds': select actions which with id is matched by regex pattern and their predecessors
                           - 'startFromDataObjectIds': select actions which have an input DataObject with id is matched by regex pattern and any dependent action (=successors)
                           - 'endWithDataObjectIds': select actions which have an output DataObject with id is matched by regex pattern and their predecessors
                           All matching is done case-insensitive.
                           Example: to filter action 'A' and its successors but only in layer L1 and L2, use the following pattern: "startFromActionIds:a;&layers:(l1|l2)"
```
